before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: nUeEGGzu6Il6K4L7+5cfCRlkYz5zf5jmMTAZvpidFG0uzHLNvQgoxe6qdQUPGRYkgLgDxlwW5aUV/zo/hKVS5+QswxSpnbGbrMCNNsYyumlUuNse5tluYDXbyx7k6IfoA7uQWOsgOPC+Kf5V6T1kuBtgbNfcW+rLHtyk6+DL8lFHj6jF6Re73Mn049Re5xb+jQXc9Uv26MbSFRALNq5B3n3nr3MOc5A/+aFDUFeKOCi3Nbm7/cRad7UmX0VYv3Ti1MJosuin0uPc+YdcUErxwysdRDy8rt89kja7zthCpH/kr8NSDv98+rAZPULvyuSZGEbpoROrh0xRcKOGVgBHNofFPku7T8Dh8n7rmGArdAwf/xh4fMuQqqMc9P13da9lC0hGHIKcuR0emKUH04ksUKtzcuKctL/e2XzGp5g/jmljzyS5P8OdOJwdBZJlDG3JG3VGkEQC8RajIxPRgKBIdL99LaCGrd+nLNtAVTeIto33M3t7reuMdA+0ndDF8IbXRSJN4tTqSDTsdCip6IjAxaXnjNCfM9YLWXZMMZooxGzX8lDKJIMRuokLzI2JVUqsk2m8Ooo4d6PVTHId0k7W1ao39VvKkUFtnOu0/j/q5m3knjM9GCDcC3ml8NmahFdfImcdqtCh8a8xqLVTrWC46dEXdPBwEu5YdQwz2PUCExY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
